name: "Build & Upload Docker Image"
description: "Build & (optionally) upload Docker Image to Docker Registry"

inputs:
  DOCKER_UPLOAD:
    description: "Boolean indicating whether the image should be uploaded to Docker registry or not."
    required: false
    default: "true"
  ENVIRONMENT:
    description: "'staging' or 'production'"
    required: true

outputs:
  tag:
    description: "Built Docker image tag (git SHA, with optional prefix)"
    value: ${{ steps.build-image.outputs.tag }}

runs:
  using: "composite"
  steps:
    - name: Run script
      id: build-image
      shell: bash
      run: bun run .github/scripts/build-image --environment "${{ inputs.ENVIRONMENT }}" --docker-upload=${{ inputs.DOCKER_UPLOAD }} --getGhaOutput=true
