name: "Build & Upload Docker Image"
description: "Build & (optionally) upload Docker Image to Docker Registry"

inputs:
  GPG_PRIVATE_KEY:
    description: "GPG Private Key"
    required: true
  GPG_PASSPHRASE:
    description: "GPG Passphrase"
    required: true
  DOCKER_UPLOAD:
    description: "Boolean indicating whether the image should be uploaded to Docker registry or not."
    required: false
    default: true
  TAG_PREFIX:
    description: "Docker tags prefix"
    required: false
  SERVER_PROFILES:
    description: "Profile(s) to apply to Codebloom instance."
    required: false
    default: prod

runs:
  using: "composite"
  steps:
    - name: Disable man-db
      uses: ./.github/composite/disable-mandb

    - name: Set up pnpm
      uses: pnpm/action-setup@master
      with:
        version: 10.24.0
        cache: true
        cache_dependency_path: js/pnpm-lock.yaml
        package_json_file: js/package.json

    - name: Set up OpenJDK 25
      uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: "25"
        cache: "maven"

    - name: Set up bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Cache Bun dependencies
      uses: actions/cache@v4
      with:
        path: ~/.bun/install/cache
        key: ${{ runner.os }}-bun-${{ hashFiles('.github/scripts/bun.lock') }}
        restore-keys: |
          ${{ runner.os }}-bun-

    - name: Install deps
      shell: bash
      run: bun install --cwd .github/scripts --frozen-lockfile

    - name: Load secrets
      uses: ./.github/composite/load-secrets
      with:
        GPG_PRIVATE_KEY: ${{ inputs.GPG_PRIVATE_KEY }}
        GPG_PASSPHRASE: ${{ inputs.GPG_PASSPHRASE }}
        UNLOAD_ENVIRONMENTS: ci,ci-app

    - name: Expose GitHub Runtime
      uses: crazy-max/ghaction-github-runtime@v3

    - name: Run script
      shell: bash
      run: bun .github/scripts/build-image.ts
      env:
        DOCKER_UPLOAD: ${{ inputs.DOCKER_UPLOAD }}
        TAG_PREFIX: ${{ inputs.TAG_PREFIX }}
        SERVER_PROFILES: ${{ inputs.SERVER_PROFILES }}
