name: "Validate DB"
description: "Validate the current db/ folder at a current commit against a database"

inputs:
  GPG_PRIVATE_KEY:
    description: "GPG Private Key"
    required: true
  GPG_PASSPHRASE:
    description: "GPG Passphrase"
    required: true
  ENVIRONMENT:
    description: '"staging" or "production"'
    required: false
    default: production

runs:
  using: "composite"
  steps:
    - name: Setup CI
      uses: ./.github/composite/setup-ci
      with:
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

    - name: Set up OpenJDK 25
      uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: "25"
        cache: "maven"

    - name: Run script
      shell: bash
      run: bun .github/scripts/run-backend-tests
