import { QuestionTopicTopic } from "@/lib/api/types/autogen/schema";
import { ApiTypeUtils } from "@/lib/api/utils/types";

/**
 * Metadata for all UserTagTag enums.
 */
export const TOPIC_METADATA_LIST: Record<
  QuestionTopicTopic,
  ApiTypeUtils.QuestionTopicMetadata
> = {
  [QuestionTopicTopic.STACK]: { name: "Stack" },
  [QuestionTopicTopic.DATA_STREAM]: { name: "Data Stream" },
  [QuestionTopicTopic.REJECTION_SAMPLING]: { name: "Rejection Sampling" },
  [QuestionTopicTopic.GEOMETRY]: { name: "Geometry" },
  [QuestionTopicTopic.COUNTING]: { name: "Counting" },
  [QuestionTopicTopic.DESIGN]: { name: "Design" },
  [QuestionTopicTopic.PROBABILITY_AND_STATISTICS]: {
    name: "Probability and Statistics",
  },
  [QuestionTopicTopic.MINIMUM_SPANNING_TREE]: { name: "Minimum Spanning Tree" },
  [QuestionTopicTopic.LINE_SWEEP]: { name: "Line Sweep" },
  [QuestionTopicTopic.NUMBER_THEORY]: { name: "Number Theory" },
  [QuestionTopicTopic.ROLLING_HASH]: { name: "Rolling Hash" },
  [QuestionTopicTopic.SEGMENT_TREE]: { name: "Segment Tree" },
  [QuestionTopicTopic.BICONNECTED_COMPONENT]: {
    name: "Biconnected Component",
  },
  [QuestionTopicTopic.MONOTONIC_STACK]: { name: "Monotonic Stack" },
  [QuestionTopicTopic.ITERATOR]: { name: "Iterator" },
  [QuestionTopicTopic.QUEUE]: { name: "Queue" },
  [QuestionTopicTopic.RADIX_SORT]: { name: "Radix Sort" },
  [QuestionTopicTopic.BUCKET_SORT]: { name: "Bucket Sort" },
  [QuestionTopicTopic.SHELL]: { name: "Shell Sort" },
  [QuestionTopicTopic.MEMOIZATION]: { name: "Memoization" },
  [QuestionTopicTopic.STRING]: { name: "String" },
  [QuestionTopicTopic.PREFIX_SUM]: { name: "Prefix Sum" },
  [QuestionTopicTopic.CONCURRENCY]: { name: "Concurrency" },
  [QuestionTopicTopic.DATABASE]: { name: "Database" },
  [QuestionTopicTopic.SHORTEST_PATH]: { name: "Shortest Path" },
  [QuestionTopicTopic.SORTING]: { name: "Sorting" },
  [QuestionTopicTopic.LINKED_LIST]: { name: "Linked List" },
  [QuestionTopicTopic.SLIDING_WINDOW]: { name: "Sliding Window" },
  [QuestionTopicTopic.SUFFIX_ARRAY]: { name: "Suffix Array" },
  [QuestionTopicTopic.DOUBLY_LINKED_LIST]: { name: "Doubly Linked List" },
  [QuestionTopicTopic.SIMULATION]: { name: "Simulation" },
  [QuestionTopicTopic.ORDERED_SET]: { name: "Ordered Set" },
  [QuestionTopicTopic.GRAPH]: { name: "Graph" },
  [QuestionTopicTopic.MATH]: { name: "Math" },
  [QuestionTopicTopic.ORDERED_MAP]: { name: "Ordered Map" },
  [QuestionTopicTopic.GAME_THEORY]: { name: "Game Theory" },
  [QuestionTopicTopic.DYNAMIC_PROGRAMMING]: { name: "Dynamic Programming" },
  [QuestionTopicTopic.RECURSION]: { name: "Recursion" },
  [QuestionTopicTopic.MONOTONIC_QUEUE]: { name: "Monotonic Queue" },
  [QuestionTopicTopic.MATRIX]: { name: "Matrix" },
  [QuestionTopicTopic.RESERVOIR_SAMPLING]: { name: "Reservoir Sampling" },
  [QuestionTopicTopic.MERGE_SORT]: { name: "Merge Sort" },
  [QuestionTopicTopic.COMBINATORICS]: { name: "Combinatorics" },
  [QuestionTopicTopic.INTERACTIVE]: { name: "Interactive" },
  [QuestionTopicTopic.BINARY_TREE]: { name: "Binary Tree" },
  [QuestionTopicTopic.RANDOMIZED]: { name: "Randomized" },
  [QuestionTopicTopic.BITMASK]: { name: "Bitmask" },
  [QuestionTopicTopic.BREADTH_FIRST_SEARCH]: { name: "Breadth-First Search" },
  [QuestionTopicTopic.STRING_MATCHING]: { name: "String Matching" },
  [QuestionTopicTopic.GREEDY]: { name: "Greedy" },
  [QuestionTopicTopic.BRAINTEASER]: { name: "Brainteaser" },
  [QuestionTopicTopic.BACKTRACKING]: { name: "Backtracking" },
  [QuestionTopicTopic.BIT_MANIPULATION]: { name: "Bit Manipulation" },
  [QuestionTopicTopic.UNION_FIND]: { name: "Union-Find" },
  [QuestionTopicTopic.BINARY_SEARCH_TREE]: { name: "Binary Search Tree" },
  [QuestionTopicTopic.TWO_POINTERS]: { name: "Two Pointers" },
  [QuestionTopicTopic.ARRAY]: { name: "Array" },
  [QuestionTopicTopic.DEPTH_FIRST_SEARCH]: { name: "Depth-First Search" },
  [QuestionTopicTopic.EULERIAN_CIRCUIT]: { name: "Eulerian Circuit" },
  [QuestionTopicTopic.TREE]: { name: "Tree" },
  [QuestionTopicTopic.BINARY_SEARCH]: { name: "Binary Search" },
  [QuestionTopicTopic.STRONGLY_CONNECTED_COMPONENT]: {
    name: "Strongly Connected Component",
  },
  [QuestionTopicTopic.ENUMERATION]: { name: "Enumeration" },
  [QuestionTopicTopic.HEAP_PRIORITY_QUEUE]: { name: "Heap / Priority Queue" },
  [QuestionTopicTopic.DIVIDE_AND_CONQUER]: { name: "Divide and Conquer" },
  [QuestionTopicTopic.HASH_FUNCTION]: { name: "Hash Function" },
  [QuestionTopicTopic.HASH_TABLE]: { name: "Hash Table" },
  [QuestionTopicTopic.TRIE]: { name: "Trie" },
  [QuestionTopicTopic.TOPOLOGICAL_SORT]: { name: "Topological Sort" },
  [QuestionTopicTopic.QUICKSELECT]: { name: "Quickselect" },
  [QuestionTopicTopic.BINARY_INDEXED_TREE]: { name: "Binary Indexed Tree" },
  [QuestionTopicTopic.COUNTING_SORT]: { name: "Counting Sort" },
  [QuestionTopicTopic.UNKNOWN]: { name: "Unknown" },
};
