ff:
  user-metrics: true

codebloom:
  scheduling:
    enabled: false
  notify:
    enabled: false

# todo: re-enable this once inside of k8s cluster
# logging:
#   structured:
#     format:
#       console: ecs
#     json:
#       add:
#         sha: "@commit.sha@"
#       stacktrace:
#         root: first
#         max-length: 12288
#         include-common-frames: true
#         include-hashes: true
