CREATE TABLE IF NOT EXISTS "Achievement" (
    id UUID NOT NULL PRIMARY KEY,
    userId UUID NOT NULL,
    iconUrl TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    isActive BOOLEAN NOT NULL DEFAULT TRUE,
    createdAt TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deletedAt TIMESTAMPTZ
);