name: "Run Notion Checks"
description: "Run Notion validation(s) on the given PR ID"

inputs:
  PR_ID:
    description: "PR ID"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup CI
      uses: ./.github/composite/setup-ci

    - name: Run script
      shell: bash
      run: bun .github/scripts/notion
      env:
        PR_ID: ${{ inputs.PR_ID }}
        GH_TOKEN: ${{ github.token }}
