name: "Run Notion Checks"
description: "Run Notion validation(s) on the given PR ID"

inputs:
  PR_ID:
    description: "PR ID"
    required: true
  GPG_PRIVATE_KEY:
    description: "GPG Private Key"
    required: true
  GPG_PASSPHRASE:
    description: "GPG Passphrase"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup CI
      uses: ./.github/composite/setup-ci
      with:
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

    - name: Run script
      shell: bash
      run: bun .github/scripts/notion
      env:
        PR_ID: ${{ inputs.PR_ID }}
        GH_TOKEN: ${{ github.token }}
