name: "Re-Deploy to DigitalOcean"
description: "Trigger a deployment to DigitalOcean and migrate the associated database."

inputs:
  GPG_PRIVATE_KEY:
    description: "GPG Private Key"
    required: true
  GPG_PASSPHRASE:
    description: "GPG Passphrase"
    required: true
  ENVIRONMENT:
    description: '"staging" or "production"'
    required: false
    default: production

runs:
  using: "composite"
  steps:
    - name: Disable man-db
      uses: ./.github/composite/disable-mandb

    - name: Set up pnpm
      uses: pnpm/action-setup@master
      with:
        version: 10.24.0
        cache: true
        cache_dependency_path: js/pnpm-lock.yaml
        package_json_file: js/package.json

    - name: Set up OpenJDK 25
      uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: "25"
        cache: "maven"

    - name: Set up bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Cache Bun dependencies
      uses: actions/cache@v4
      with:
        path: ~/.bun/install/cache
        key: ${{ runner.os }}-bun-${{ hashFiles('.github/scripts/bun.lock') }}
        restore-keys: |
          ${{ runner.os }}-bun-

    - name: Install deps
      shell: bash
      run: bun install --cwd .github/scripts --frozen-lockfile

    - name: Load secrets
      uses: ./.github/composite/load-secrets
      with:
        GPG_PRIVATE_KEY: ${{ inputs.GPG_PRIVATE_KEY }}
        GPG_PASSPHRASE: ${{ inputs.GPG_PASSPHRASE }}
        UNLOAD_ENVIRONMENTS: ci

    - name: Expose GitHub Runtime
      uses: crazy-max/ghaction-github-runtime@v3

    - name: Check for DB changes
      id: db-changes
      shell: bash
      if: ${{ inputs.ENVIRONMENT == 'staging' }}
      run: |
        git fetch origin main:main
        if git diff --name-only main...${{ needs.getPRHead.outputs.sha }} | grep -q '^db/'; then
          echo "changed=true" >> $GITHUB_OUTPUT
          echo "DB changes detected"
        else
          echo "changed=false" >> $GITHUB_OUTPUT
          echo "No DB changes detected"
        fi

    - name: Migrate Staging DB
      if: ${{ inputs.ENVIRONMENT == 'production' || (inputs.ENVIRONMENT == 'staging' && steps.db-changes.outputs.changed == 'true') }}
      shell: bash
      run: ./mvnw flyway:migrate -Dflyway.locations=filesystem:./db/migration

    - name: Run script
      shell: bash
      run: bun .github/scripts/redeploy.ts
      env:
        DOCKER_UPLOAD: ${{ inputs.DOCKER_UPLOAD }}
        TAG_PREFIX: ${{ inputs.TAG_PREFIX }}
        SERVER_PROFILES: ${{ inputs.SERVER_PROFILES }}
        DIGITALOCEAN_PROJECT_ID: ${{ inputs.ENVIRONMENT == 'staging' && env.STG_DIGITAL_OCEAN_PROJECT_ID || env.PROD_DIGITAL_OCEAN_PROJECT_ID }}
        DIGITALOCEAN_PAT: ${{ inputs.ENVIRONMENT == 'staging' && env.STG_DIGITAL_OCEAN_PAT || env.PROD_DIGITAL_OCEAN_PAT }}
