name: Deploy Web Service
description: Builds web image and deploys to k8s manifests

inputs:
  ENVIRONMENT:
    description: "'staging' or 'production'"
    required: true

runs:
  using: composite
  steps:
    - name: Build and push web image
      id: build-image
      shell: bash
      run: bun run .github/scripts/build-image --environment "${{ inputs.ENVIRONMENT }}" --docker-upload=true --getGhaOutput=true

    - name: Deploy web image tag
      shell: bash
      run: bun run .github/scripts/deploy --environment "${{ inputs.ENVIRONMENT }}" --type web --newTagVersion "${{ steps.build-image.outputs.tag }}"
