name: "Load Secrets"
description: "Load secrets & mask all loaded secrets"
inputs:
  GPG_PRIVATE_KEY:
    description: "GPG Private Key"
    required: true
  GPG_PASSPHRASE:
    description: "GPG Passphrase"
    required: true
  UNLOAD_ENVIRONMENTS:
    description: "Comma separated string of what environment files to load"
runs:
  using: "composite"
  steps:
    - name: Disable man-db
      uses: ./.github/composite/disable-mandb

    - name: Check GPG secret key & passphrase exists
      shell: bash
      run: |
        [ -n "${GPG_PRIVATE_KEY:-}" ] && echo "GPG_PRIVATE_KEY found" || echo "GPG_PRIVATE_KEY missing or empty"
        [ -n "${GPG_PASSPHRASE:-}" ] && echo "GPG_PASSPHRASE found" || echo "GPG_PASSPHRASE missing or empty"
      env:
        GPG_PRIVATE_KEY: ${{ inputs.GPG_PRIVATE_KEY }}
        GPG_PASSPHRASE: ${{ inputs.GPG_PASSPHRASE }}

    - name: Load GPG secret key
      uses: crazy-max/ghaction-import-gpg@v6
      with:
        gpg_private_key: ${{ inputs.GPG_PRIVATE_KEY }}
        passphrase: ${{ inputs.GPG_PASSPHRASE }}

    - name: Install git-crypt
      uses: flydiverny/setup-git-crypt@v4

    - name: Verify git-crypt version
      shell: bash
      run: git-crypt --version

    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Cache Bun dependencies
      uses: actions/cache@v4
      with:
        path: ~/.bun/install/cache
        key: ${{ runner.os }}-bun-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-bun-

    - name: Install deps
      shell: bash
      run: bun install --cwd .github/scripts --frozen-lockfile

    - name: Run script
      shell: bash
      run: bun .github/scripts/load-secrets.ts
      env:
        UNLOAD_ENVIRONMENTS: ${{ inputs.UNLOAD_ENVIRONMENTS }}
