name: "Send PR Message"
description: "Post an arbitrary message to a pull request"

# requires the following permissions
# permissions:
#   issues: write

inputs:
  prId:
    description: "PR ID number"
    required: true
  message:
    description: "Message body to post on the PR"
    required: true
  token:
    description: "GitHub token to use (defaults to GITHUB_TOKEN)"
    required: false
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - name: Setup CI
      uses: ./.github/composite/setup-ci
      with:
        GITHUB_TOKEN: ${{ inputs.token }}

    - name: Run script
      shell: bash
      run: bun .github/scripts/send-message/gha
      env:
        PR_ID: ${{ inputs.prId }}
        MESSAGE: ${{ inputs.message }}
