name: "Send PR Message"
description: "Post an arbitrary message to a pull request"

# requires the following permissions
# permissions:
#   issues: write

inputs:
  prId:
    description: "PR ID number"
    required: true
  message:
    description: "Message body to post on the PR"
    required: true
  token:
    description: "GitHub token to use (defaults to GITHUB_TOKEN)"
    required: false
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - name: Post PR Message
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.token }}
        script: |
          const prId = ${{ inputs.prId }};
          const message = ${{ toJSON(inputs.message) }};

          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: parseInt(prId, 10),
            body: message
          });
