alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
domains:
  - domain: codebloom.patinanetwork.org
    type: PRIMARY
features:
  - buildpack-stack=ubuntu-22
ingress:
  rules:
    - component:
        name: codebloom
      match:
        path:
          prefix: /
maintenance: {}
name: codebloom-prod
region: nyc
services:
  - name: codebloom
    health_check:
      failure_threshold: 9
      http_path: /api
      period_seconds: 10
      success_threshold: 1
      timeout_seconds: 1
    http_port: 8080
    image:
      registry: tahminator
      registry_type: DOCKER_HUB
      repository: codebloom
      tag: latest
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-1gb-fixed
    liveness_health_check:
      failure_threshold: 9
      http_path: /api
      period_seconds: 10
      success_threshold: 1
      timeout_seconds: 1
# environment variables are decrypted & inputted into yaml in ci
