name: "Verify PR Description"
description: "Ensure the GH PR description is filled out"

inputs:
  PR_ID:
    description: "PR ID"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup CI
      uses: ./.github/composite/setup-ci

    - name: Run script
      id: run_script
      shell: bash
      run: bun .github/scripts/pr-description-check --prId=${{ inputs.PR_ID }}
