name: CI/CD
run-name: Running CI/CD on ${{ github.actor }}'s commits

on:
  pull_request:

permissions:
  contents: write
  issues: write
  pull-requests: write

concurrency:
  group: auto-approval-${{ github.ref }}
  cancel-in-progress: true

jobs:
  autoApproval:
    name: Run auto approval script
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup CI
        uses: ./.github/composite/setup-ci
        with:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Run script
        shell: bash
        run: bun .github/scripts/auto-approval
        env:
          PR_ID: ${{ github.event.pull_request.number }}
