name: Run Tests
run-name: Running tests on ${{ github.actor }}'s commits


on:
    push:
        branches:
            - main
    pull_request:

jobs:
    frontend-tests:
        name: Frontend Tests
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v4
    
          - name: Set up Node.js
            uses: actions/setup-node@v4
            with:
              node-version: 20

          - name: Fix a bug with corepack by installing corepack globally
            run: npm i -g corepack@latest
            working-directory: js

          - name: Install Dependencies
            run: corepack enable pnpm && pnpm i --frozen-lockfile
            working-directory: js

          - name: Run full suite of tests + linters + autoformatters
            run: pnpm run test
            working-directory: js

    
