name: Deploy to DigitalOcean
run-name: Deploying on ${{ github.actor }}'s commits

# on:
#     push:
#         branches:
#             - main
#     pull_request:

on:
    workflow_run:
        workflows: ["Run Tests"]
        types:
            - completed

jobs:
    buildImage:
        name: Build Docker image
        runs-on: ubuntu-latest

        if: >
            ${{ github.event.workflow_run.conclusion == 'success' &&
            github.event.workflow_run.head_branch == 'main' }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Log in to DigitalOcean Container Registry
              uses: docker/login-action@v3
              with:
                  registry: docker.io
                  username: tahminator
                  password: ${{ secrets.DOCKER_HUB_PAT }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: infra/Dockerfile
                  push: true
                  tags: tahminator/codebloom:latest
