name: Drop CI Database
run-name: Drop CI Database

on:
    repository_dispatch:
        types: [drop-ci-db-command]

permissions:
    contents: write
    issues: write
    pull-requests: write

jobs:
    dropCiDb:
        name: Drop CI DB

        runs-on: ubuntu-latest

        env:
            DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
            DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
            DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
            DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
            DATABASE_USER: ${{ secrets.DATABASE_USER }}

        steps:
            - name: Comment on PR
              uses: actions/github-script@v7
              with:
                  script: |
                      const prId = '${{ github.event.client_payload.slash_command.args.named.prId }}';
                      const runUrl = `${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;

                      await github.rest.issues.createComment({
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          issue_number: parseInt(prId, 10),
                          body: `The command to drop the CI database has been triggered. [View action run](${runUrl})`
                      });

            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Set up OpenJDK 21
              uses: actions/setup-java@v4
              with:
                  distribution: "temurin"
                  java-version: "21"
                  cache: "maven"

            - name: Verify Java version
              run: |
                  java -version
                  javac -version
                  echo "JAVA_HOME=$JAVA_HOME"

            - name: Run clean CI DB command
              run: ./mvnw flyway:clean -Dflyway.cleanDisabled=false -Dflyway.locations=filesystem:./db
