name: Pull Request Commands
run-name: Running pull request command(s) on ${{ github.actor }}'s commits

on:
    issue_comment:
        types: [created]

permissions:
    contents: read
    issues: write
    pull-requests: write

jobs:
    cleanCiDb:
        runs-on: ubuntu-latest
        if: ${{ github.event.issue.pull_request != null && contains(github.event.comment.body, '/clean') }}

        env:
            DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
            DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
            DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
            DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
            DATABASE_USER: ${{ secrets.DATABASE_USER }}

        steps:
            - name: Debug workflow trigger
              run: |
                  echo "Comment body: ${{ github.event.comment.body }}"
                  echo "Is PR: ${{ github.event.issue.pull_request }}"
                  echo "Contains /clean: ${{ contains(github.event.comment.body, '/clean') }}"

            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Set up OpenJDK 21
              uses: actions/setup-java@v4
              with:
                  distribution: "temurin"
                  java-version: "21"

            - name: Verify Java version
              run: |
                  java -version
                  javac -version
                  echo "JAVA_HOME=$JAVA_HOME"

            - name: Clean CI DB
              run: ./mvnw flyway:clean -Dflyway.cleanDisabled=false -Dflyway.locations=filesystem:./db/migration
